services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: bridge
    ports:
      - ${flaresolverr_api_port}:8191
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=${flaresolver_uid}
      - PGID=${flaresolverr_gid}
      - TZ=${TZ}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 2048M
#        reservations:
#          cpus: '0.05'
#          memory: 256M